name: Crates.io Publish
description: Publish library to crates.io

runs:
    using: composite
    steps:
        - uses: actions/checkout@v6
        - name: Build Release & publish crate
          shell: bash
          run: |
              cargo build --release --all-features
              cargo doc --release --all-features
              cargo publish --all-features
