name: Crates.io Publish
description: Publish library to crates.io

inputs:
    cargo-extra-args:
        description: "Extra cargo args (e.g. --all-features, --features foo,bar, or empty string)"
        required: false
        default: "--all-features"

runs:
    using: composite
    steps:
        - uses: actions/checkout@v6
        - name: Build Release & publish crate
          shell: bash
          run: |
              cargo build --release ${{ inputs.cargo-extra-args }}
              cargo doc --release ${{ inputs.cargo-extra-args }}
              cargo publish ${{ inputs.cargo-extra-args }}
