name: "Rust Coverage (llvm-cov)"
description: "Generate code coverage reports using cargo-llvm-cov"

runs:
    using: "composite"
    steps:
        - name: Install cargo-llvm-cov
          shell: bash
          run: |
              if ! command -v cargo-llvm-cov &> /dev/null; then
                cargo install cargo-llvm-cov --locked
              fi

        - name: Run coverage
          shell: bash
          run: |
              cargo llvm-cov clean --workspace
              cargo llvm-cov --workspace --all-features --lcov --output-path lcov.info
