name: "Prerequisites Ubuntu"
description: "Install prerequisites for Ubuntu dev environment"

runs:
    using: "composite"
    steps:
        - name: Install Prerequisites
          shell: bash
          run: |
              sudo apt update
              sudo apt install libwebkit2gtk-4.1-dev \
                build-essential \
                curl \
                wget \
                file \
                libxdo-dev \
                libssl-dev \
                libayatana-appindicator3-dev \
                librsvg2-dev
