name: "Rust Test"
description: "Run cargo test"

inputs:
    cargo-extra-args:
        description: "Extra cargo args (e.g. --all-features, --features foo,bar, or empty string)"
        required: false
        default: "--all-features"

runs:
    using: "composite"
    steps:
        - name: Test
          shell: bash
          run: cargo test --workspace --all-targets ${{ inputs.cargo-extra-args }}
