name: "Rust Fmt"
description: "Check Rust code formatting"

runs:
    using: "composite"
    steps:
        - name: Run rustfmt
          shell: bash
          run: |
              rustup component add rustfmt
              cargo fmt --all -- --check
