name: Dioxus Android Setup
description: |
    Set up Rust, Java, and Android SDK/NDK for Dioxus Android builds.
    Assumes prior os-prerequisites and dioxus-setup steps.

runs:
    using: composite
    steps:
        - name: Add Android Rust targets
          shell: bash
          run: |
              rustup target add \
                aarch64-linux-android \
                armv7-linux-androideabi \
                i686-linux-android \
                x86_64-linux-android

        - name: Set up Java
          uses: actions/setup-java@v4
          with:
              distribution: temurin
              java-version: "17"

        - name: Set up Android SDK and NDK
          shell: bash
          run: |
              set -euo pipefail

              SDK_ROOT="$PWD/android-sdk"
              CMDLINE_ZIP="commandlinetools-linux-13114758_latest.zip"

              wget -q https://dl.google.com/android/repository/$CMDLINE_ZIP
              unzip -q $CMDLINE_ZIP

              mkdir -p "$SDK_ROOT/cmdline-tools"
              mv cmdline-tools "$SDK_ROOT/cmdline-tools/latest"

              echo "ANDROID_HOME=$SDK_ROOT" >> "$GITHUB_ENV"
              echo "ANDROID_SDK_ROOT=$SDK_ROOT" >> "$GITHUB_ENV"

              yes | "$SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses

              "$SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
                "platform-tools" \
                "platforms;android-36" \
                "build-tools;36.0.0" \
                "ndk;26.1.10909125"

              echo "ANDROID_NDK_HOME=$SDK_ROOT/ndk/26.1.10909125" >> "$GITHUB_ENV"
