name: Dioxus Android Setup
description: |
    Set up Rust, Java, and Android SDK/NDK for Dioxus Android builds.
    Assumes prior os-prerequisites and dioxus-setup steps.

runs:
    using: composite
    steps:
        - name: Add Android Rust targets
          shell: bash
          run: |
              rustup target add \
                aarch64-linux-android \
                armv7-linux-androideabi \
                i686-linux-android \
                x86_64-linux-android

        - name: Set up Java
          uses: actions/setup-java@v4
          with:
              distribution: temurin
              java-version: "17"

        - name: Set up Android SDK and NDK
          shell: bash
          run: |
              wget https://dl.google.com/android/repository/commandlinetools-linux-13114758_latest.zip
              unzip commandlinetools-linux-13114758_latest.zip
              mkdir -p android-sdk/cmdline-tools
              ls -al .
              mv cmdline-tools android-sdk/cmdline-tools/latest
              ls -al android-sdk/cmdline-tools/latest

              export ANDROID_HOME=$PWD/android-sdk
              export ANDROID_SDK_ROOT="$ANDROID_HOME"
              export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$PATH"

              echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
              echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
              echo "PATH=$PATH" >> $GITHUB_ENV
              exit -1;

              # yes | sdkmanager --licenses
              # yes | sdkmanager \
              #   "platform-tools" \
              #   "platforms;android-36" \
              #   "build-tools;36.0.0" \
              #   "ndk;26.1.10909125"
              # echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/26.1.10909125" >> $GITHUB_ENV
