name: "Rust Clippy"
description: "Run Clippy lints with warnings as errors"

inputs:
    cargo-extra-args:
        description: "Extra cargo args (e.g. --all-features, --features foo,bar, or empty string)"
        required: false
        default: "--all-features"

runs:
    using: "composite"
    steps:
        - name: Run Clippy
          shell: bash
          run: |
              rustup component add clippy
              cargo clippy --workspace --all-targets ${{ inputs.cargo-extra-args }} -- -D warnings
