name: "Rust Clippy"
description: "Run Clippy lints with warnings as errors"

runs:
    using: "composite"
    steps:
        - name: Run Clippy
          shell: bash
          run: |
              rustup component add clippy
              cargo clippy --workspace --all-targets --all-features -- -D warnings
