name: "Run lingora-cli"
description: "Download and run lingora-cli"
inputs:
    version:
        description: "GitHub release tag (e.g. v1.2.3 or latest)"
        required: false
        default: "latest"
    args:
        description: "Arguments to pass to lingora-cli"
        required: false
        default: ""

runs:
    using: "composite"
    steps:
        - name: Detect non-Windows platform
          if: runner.os != 'Windows'
          shell: bash
          run: |
              set -euo pipefail

              OS="$(uname -s)"
              ARCH="$(uname -m)"

              case "$OS" in
                Linux)  TARGET_OS="unknown-linux-gnu" ;;
                Darwin) TARGET_OS="apple-darwin" ;;
                *) echo "Unsupported OS: $OS"; exit 1 ;;
              esac

              case "$ARCH" in
                x86_64|amd64) TARGET_ARCH="x86_64" ;;
                arm64|aarch64) TARGET_ARCH="aarch64" ;;
                *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
              esac

              echo "TARGET=${TARGET_ARCH}-${TARGET_OS}" >> "$GITHUB_ENV"

        - name: Detect Windows platform
          if: runner.os == 'Windows'
          shell: bash
          run: |
              echo "TARGET=x86_64-pc-windows-gnu" >> "$GITHUB_ENV"

        - name: Download lingora-cli
          shell: bash
          run: |
              set -euo pipefail

              VERSION="${{ inputs.version }}"
              if [[ "$VERSION" == "latest" ]]; then
                URL="https://github.com/nigeleke/lingora/releases/latest/download/lingora-cli-$TARGET"
              else
                URL="https://github.com/nigeleke/lingora/releases/download/$VERSION/lingora-cli-$TARGET"
              fi

              echo "Downloading $URL"
              curl -fsSL "$URL" -o lingora-cli

        - name: Make executable
          if: runner.os != 'Windows'
          shell: bash
          run: chmod +x lingora-cli

        - name: Run lingora-cli
          shell: bash
          run: |
              ./lingora-cli ${{ inputs.args }}
