name: Site publish
description: Upload README, rust docs & llvm-coverage-report to gh-pages

inputs:
    cargo-extra-args:
        description: "Extra cargo args (e.g. --all-features, --features foo,bar, or empty string)"
        required: false
        default: "--all-features"

runs:
    using: composite
    steps:
        - name: Checkout
          uses: actions/checkout@v6

        - name: Prepare site directory
          shell: bash
          run: |
              set -e
              mkdir -p site/_layouts
              mkdir -p site/assets/css
              if [ -f README.md ]; then
                cp README.md site/index.md
              fi
              [ -d docs ] && cp -R docs/* site/ || true
              [ -d target/doc ] && cp -R target/doc site/doc || true
              [ -d target/llvm-cov ] && cp -R target/llvm-cov site/coverage || true

              REPO_NAME="${GITHUB_REPOSITORY##*/}"
              cat > site/_config.yml << 'EOF'
              title: ${REPO_NAME}
              markdown: kramdown
              theme: null
              EOF

              cat > site/_layouts/default.html << 'EOF'
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>niGel eKe - personal site</title>
                <link rel="stylesheet" href="{{ '/assets/css/main.css' | relative_url }}">
                <link rel="stylesheet" href="{{ '/assets/css/title.css' | relative_url }}">
                <link rel="stylesheet" href="{{ '/assets/css/menu.css' | relative_url }}">
                <link rel="stylesheet" href="{{ '/assets/css/external_link.css' | relative_url }}">
              </head>
              <body>
                <main>
                  <header>
                    <a class="title" href="https://nigeleke.github.io/">niGel eKe - personal site</a>
                    <nav id="menu-nav"}>
                      <a href="https://nigeleke.github.io>home</a>
                      <a href="https://nigeleke.github.io/italian>italian</a>
                      <a href="https://nigeleke.github.io/projects>projects</a>
                      <a href="https://nigeleke.github.io/reference>reference</a>
                      <a href="https://nigeleke.github.io/apis>apis</a>
                      <a href="https://nigeleke.github.io/useful_info>useful info</a>
                    </nav>
                  </header>
                  <section>
                    {{ content }}
                  </section>
                  <footer>
                    <span>Copyright © 2025-2026; Nigel Eke. All rights reserved.</span>
                    <span>Made with <a class="external-link" href="https://dioxuslabs.com/" target="_blank">Dioxus</a></span>
                  </footer>
                </main>
              </body>
              </html>
              EOF

        - name: Build with Jekyll
          uses: actions/jekyll-build-pages@v1
          with:
              source: ./site
              destination: ./_site

        - name: Upload Pages artifact
          uses: actions/upload-pages-artifact@v4
          with:
              path: ./_site

        - name: Deploy
          id: deployment
          uses: actions/deploy-pages@v4
