name: Site publish
description: Upload README, rust docs & llvm-coverage-report to gh-pages

inputs:
    cargo-extra-args:
        description: "Extra cargo args (e.g. --all-features, --features foo,bar, or empty string)"
        required: false
        default: "--all-features"

runs:
    using: composite
    steps:
        - name: Checkout
          uses: actions/checkout@v6

        - name: Prepare site directory
          shell: bash
          run: |
              set -e
              mkdir -p site/_layouts
              mkdir -p site/assets/css
              if [ -f README.md ]; then
                cp README.md site/index.md
              fi
              [ -d docs ] && cp -R docs/* site/ || true
              [ -d target/doc ] && cp -R target/doc site/doc || true
              [ -d target/llvm-cov ] && cp -R target/llvm-cov site/coverage || true

              REPO_NAME="${GITHUB_REPOSITORY##*/}"
              cat > site/_config.yml << 'EOF'
              title: ${REPO_NAME}
              markdown: kramdown
              theme: null
              EOF

              cat > site/_layouts/default.html << 'EOF'
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>niGel eKe - project site</title>
                <link rel="stylesheet" href="{{ '/assets/css/style.css' | relative_url }}">
              </head>
              <body>
                <main>
                  <header>
                    <a class="title" href="https://nigeleke.github.io/">niGel eKe - project site</a>
                  </header>
                  <section>
                    {{ content }}
                  </section>
                  <footer>
                    <span>Copyright © 2025-2026; Nigel Eke. All rights reserved.</span>
                  </footer>
                </main>
              </body>
              </html>
              EOF

              cat > site/assets/css/style.css << 'EOF'
              :root {
                  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;
                  --border-colour: #546f82;
                  --border-colour-highlight: hsl(from var(--border-colour) h s 60%);
                  --border-text-colour: #f8f8ff;
              }

              @media (prefers-color-scheme: light) {
                  :root {
                      --background-colour: #f8f8ff;
                      --text-colour: #616161;
                      --image-background-highlight: hsl(
                          from var(--background-colour) h s 97%
                      );
                  }
              }

              @media (prefers-color-scheme: dark) {
                  :root {
                      --background-colour: #4a4a4a;
                      --text-colour: var(--border-text-colour);
                      --image-background-highlight: hsl(
                          from var(--background-colour) h s 60%
                      );
                  }
              }

              html,
              body {
                  background-color: var(--background-colour);
                  color: var(--text-colour);
                  margin: 0px;
                  padding: 0px;
              }

              main {
                  height: 100svh;
                  display: grid;
                  grid-template-rows: auto 1fr auto;
              }

              header,
              footer {
                  background-color: var(--border-colour);
                  color: var(--border-text-colour);
                  padding: 20px;
              }

              header a,
              footer a {
                  color: var(--border-text-colour);
              }

              header a:hover,
              footer a:hover {
                  background-color: var(--border-colour-highlight);
              }

              header {
                  display: flex;
                  justify-content: space-between;
              }

              main > section {
                  padding-top: 20px;
                  padding-bottom: 10px;
                  width: 60%;
                  justify-self: center;
                  display: grid;
                  justify-content: stretch;
                  align-content: start;
                  overflow-y: auto;
              }

              footer {
                  font-size: smaller;
                  display: flex;
                  justify-content: space-between;
              }

              h1 {
                  font-size: x-large;
              }

              h2 {
                  font-size: larger;
                  font-style: italic;
              }

              a {
                  text-decoration: none;
                  color: var(--text-colour);
              }

              a:hover {
                  background-color: var(--border-colour-highlight);
                  color: var(--border-text-colour);
              }

              table {
                  width: 98%;
                  border-collapse: collapse;
              }

              tr:first-child {
                  border-top: var(--border-colour-highlight) 1px solid;
              }

              tr:last-child {
                  border-bottom: var(--border-colour-highlight) 1px solid;
              }

              th:first-child,
              td:first-child {
                  border-left: var(--border-colour-highlight) 1px solid;
              }

              th,
              td {
                  border-right: var(--border-colour-highlight) 1px solid;
                  padding-left: 5px;
                  padding-right: 5px;
              }

              th {
                  text-align: left;
              }

              img {
                  background-color: var(--image-background-highlight);
                  padding: 10px;
                  border-radius: 10px;
              }

              .menu-button {
                  background-color: var(--border-colour);
                  border: none;
              }
              .menu-icon {
                  height: 16px;
              }

              nav {
                  background-color: var(--border-colour);
                  display: flex;
                  gap: 10px;
              }

              .title {
                  font-size: xx-large;
              }

              .external-link::after {
                  content: " 🔗";
                  font-size: 0.8em;
                  margin-left: 5px;
                  color: inherit;
              }
              EOF

        - name: Build with Jekyll
          uses: actions/jekyll-build-pages@v1
          with:
              source: ./site
              destination: ./_site

        - name: Upload Pages artifact
          uses: actions/upload-pages-artifact@v4
          with:
              path: ./_site

        - name: Deploy
          id: deployment
          uses: actions/deploy-pages@v4
