name: Site publish
description: Upload README, rust docs & llvm-coverage-report to gh-pages

inputs:
    cargo-extra-args:
        description: "Extra cargo args (e.g. --all-features, --features foo,bar, or empty string)"
        required: false
        default: "--all-features"

runs:
    using: composite
    steps:
        - name: Checkout
          uses: actions/checkout@v6
          with:
              fetch-depth: 0

        - name: Move documentation to temp folder
          shell: bash
          run: |
              mkdir docs0
              touch docs0/.nojekyll
              ls -la          # â† ADD THIS: shows what's actually in the current directory
              if [ -f README.md ]; then
                  cp README.md docs0/
              else
                  echo "README.md NOT FOUND in $(pwd)"
                  ls -la          # show again for proof
              fi
              [ -d docs ] && cp -R docs docs0/ || true
              [ -d target/doc ] && cp -R target/doc docs0/ || true
              [ -d target/llvm-cov ] && cp -R target/llvm-cov docs0/ || true

        - name: Update gh-pages
          shell: bash
          run: |
              git config --global user.email "nigeleke@users.noreply.github.com"
              git config --global user.name "Nigel Eke"

              VERSION=$(git describe --abbrev=0 --tags 2>/dev/null || echo "dev")

              git fetch origin gh-pages
              git checkout gh-pages
              git rm -rf docs
              rm -rf docs
              mv docs0 docs
              git add docs
              git commit -m "Release $VERSION" || echo "No changes"
              git push origin gh-pages
