name: "Rust Setup"
description: "Install Rust toolchain and enable cargo caching"

inputs:
    toolchain:
        description: "Rust toolchain"
        required: false
        default: "stable"

runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v4

        - name: Install Rust
          uses: dtolnay/rust-toolchain@master
          with:
              toolchain: ${{ inputs.toolchain }}
