name: "Cargo Audit"
description: "Install and run cargo-audit"

runs:
    using: "composite"
    steps:
        - name: Install cargo-audit
          shell: bash
          run: cargo install cargo-audit --locked

        - name: Run cargo audit
          shell: bash
          run: cargo audit
