name: "Prerequisites Windows"
description: "Install prerequisites for Windows dev environment"

runs:
    using: "composite"
    steps:
        - name: Install Prerequisites
          shell: bash
          run: echo "TODO"
