name: Docker publish
description: Upload llvm-codecov report to codecov

inputs:
    platforms:
        description: "Comma-separated list of platforms to build for (e.g., linux/amd64,linux/arm64)"
        required: true
    tags:
        description: "Comma-separated list of tags to apply to the pushed image"
        required: true

runs:
    using: composite
    steps:
        - uses: docker/login-action@v3
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

        - uses: docker/setup-qemu-action@v3

        - uses: docker/setup-buildx-action@v3
          with:
              platforms: ${{ inputs.platforms }}

        - uses: docker/build-push-action@v6
          with:
              file: docker/Dockerfile
              context: .
              push: true
              platforms: ${{ inputs.platforms }}
              tags: ${{ inputs.tags }}
