name: "Dioxus Setup"
description: "Install Dioxus toolchain and cache"

inputs:
    toolchain:
        description: "Rust toolchain"
        required: false
        default: "nightly"

runs:
    using: "composite"
    steps:
        - uses: nigeleke/github/actions/rust-setup@main
          with:
              toolchain: ${{ inputs.toolchain }}

        - name: Install Dioxus
          shell: bash
          run: |
              cargo install dioxus-cli --locked

        - name: Cache cargo builds
          uses: Swatinem/rust-cache@v2
          with:
              cache-all-crates: true
