name: Dioxus Multi-Platform Release

on:
    push:
        tags:
            - "v*"

jobs:
    setup:
        runs-on: ubuntu-latest
        outputs:
            os-matrix: ${{ steps.matrix.outputs.os-matrix }}
        steps:
            - id: matrix
              uses: nigeleke/github/.github/actions/dioxus-build-release@main
              with:
                  platforms: web,desktop,android
                  profile: release

    build:
        needs: setup
        strategy:
            matrix:
                os: ${{ fromJson(needs.setup.outputs.os-matrix) }}
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: nigeleke/github/.github/actions/dioxus-build-release@main
              with:
                  platforms: web,desktop,android
                  profile: release
                  release-tag: ${{ github.ref_name }}
